name: school-service

services:
  school-service:
    image: hendirepo/school-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-service
    depends_on:
      - pgdb
    ports:
      - 3333:3333
    restart: always
    env_file:
      - app.env

  pgdb:
    image: postgres:latest
    container_name: pgdb
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - pgdb-volume:/var/lib/postgresql/data
    restart: always

volumes:
  pgdb-volume: